Updated README.md
facebookresearch/dinov2 pull request #5
Opened 2023-04-17 23:04 UTC by Aryanutkarsh

<h2>Improved the Readability </h2>

- Fixed the broken link to the research paper
- Center aligned the tables(to improve readability)
- Fixed grammatical error

2023-04-18 00:44 UTC, Xrenya commented
@Aryanutkarsh it should be `DINOv2 models produce` without `s`. It was correct.

2023-04-18 21:17 UTC, patricklabatut commented
> Fixed the broken link to the research paper

Note there is already a paper link in the link bar just above, so I would perhaps not call this broken and I am not sure this is exactly needed (but fine).

> Center aligned the tables

That's also not exactly critical (but again fine). However this does not seem to work as intended, some of the contents of the table (e.g. "ViT-g/14") gets centered as well (using GitHub's markdown preview).

2023-04-18 21:18 UTC, patricklabatut commented on README.md
> +</div>
Let's not center this link bar.

2023-04-18 21:18 UTC, patricklabatut requested changes
Thanks, back to you to address the comments.

2023-04-18 21:51 UTC, patricklabatut commented on README.md
>  <table>
After doing a bit of research, it seems styling the table to auto-center is the proper way to achieve this:

```
<table style="margin: auto">
```

2023-04-18 21:51 UTC, patricklabatut commented on README.md
> +<div align="center">
Nit: keep an empty line between title and table thanks.

2023-04-18 21:51 UTC, patricklabatut commented on README.md
> +<div align="center">
Same comment as above on styling the table instead (and please keep a separating blank line).

2023-04-18 21:52 UTC, patricklabatut commented on README.md
> +
Nit: Remove left-over whitespace from the previous changes.

2023-04-18 22:09 UTC, Aryanutkarsh commented
@patricklabatut sir thank you so much for being so understanding and guiding. I am new to open source,I want work with people like you rather making pr to first contribution repos.This thought me how to resolve the reviews 

### Thank you Sir 🙂

2023-04-18 22:43 UTC, patricklabatut commented
@Aryanutkarsh Remove the div elements that were introduced, I don't think they should not be needed anymore with the "margin: auto" styling. Test and if that's indeed fine, that should be good to merge.

2023-04-18 22:54 UTC, Aryanutkarsh commented
Done sir 👍

2023-04-19 21:01 UTC, patricklabatut approved these changes

2023-04-19 21:02 UTC, merged